import {
  AssetsModel,
  EmployeesReportModel,
  InstitutionModel,
  MaterialReportModel,
  SalarySummaryModel,
  StaffInfoModel,
  StaffModel,
  StaffMovementModel,
  StaffSalaryModel,
} from "@/lib/api-service";
import { TurnoverBalanceModel } from "@/lib/api-service/model/1c/turnover-balance-model";
import { AwardsModel } from "@/lib/api-service/model/1c/awards-model";
import { DisciplinaryModel } from "@/lib/api-service/model/1c/disciplinary-model";

// Mock data for testing
export const MOCK_STAFF_DATA: Array<StaffModel> = [
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "663fd553-311d-11ee-8123-8030e02da23e",
    staff_iin: "711105300864",
    lastname: "САЛИМБАЕВ",
    firstname: "ЖАНАТ",
    patronymic: "САКЫТАЕВИЧ",
    gender: "Мужской",
    birth_date: "05.11.1971",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "6a4324f5-52df-11ea-a6ae-1c1b0ded7778",
    department_name: "Административно-управленческий персонал",
    department_sort: "1",
    position: "29652026-b896-11eb-8115-8030e02da23e",
    position_name: "СОВЕТНИК-КОМПЛАЕНС ОФИЦЕР",
    position_sort: "4",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "7530343f-cb2e-11ef-8147-8030e02da23e",
    staff_iin: "870313400503",
    lastname: "Уталиева",
    firstname: "Лунара",
    patronymic: "Курманбековна",
    gender: "Женский",
    birth_date: "13.03.1987",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "6a4324f9-52df-11ea-a6ae-1c1b0ded7778",
    department_name: "Отдел технологического обеспечения",
    department_sort: "7",
    position: "b6e0647b-5313-11ea-a6ae-1c1b0ded7778",
    position_name: "ГЛАВНЫЙ СПЕЦИАЛИСТ",
    position_sort: "8",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "fc6c785d-e763-11ea-810a-8030e02da23e",
    staff_iin: "750414350082",
    lastname: "Молдаханов",
    firstname: "Бекет",
    patronymic: "Кадырбекович",
    gender: "Мужской",
    birth_date: "14.04.1975",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "935f8164-129c-11ef-8134-8030e02da23e",
    department_name: "Управление активами",
    department_sort: "11",
    position: "1bb05d8d-5315-11ea-a6ae-1c1b0ded7778",
    position_name: "НАЧАЛЬНИК УПРАВЛЕНИЯ",
    position_sort: "6",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "e15fcf10-f356-11ea-810b-8030e02da23e",
    staff_iin: "860308403310",
    lastname: "ДЮСЕБАЕВА",
    firstname: "МАДИНА",
    patronymic: "КАРАКУЛОВНА",
    gender: "Женский",
    birth_date: "08.03.1986",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "26583111-a44e-11ea-8104-8030e02da23e",
    department_name: "Отдел сопровождения проектов",
    department_sort: "12",
    position: "1bb05d8c-5315-11ea-a6ae-1c1b0ded7778",
    position_name: "НАЧАЛЬНИК ОТДЕЛА",
    position_sort: "7",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "540bfc48-3b8e-11eb-8110-8030e02da23e",
    staff_iin: "630126301510",
    lastname: "Машрапов",
    firstname: "Оралбек",
    patronymic: "Солтанович",
    gender: "Мужской",
    birth_date: "26.01.1963",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "6a4324fd-52df-11ea-a6ae-1c1b0ded7778",
    department_name: "Управление материально-технического обеспечения",
    department_sort: "9",
    position: "1bb05d8d-5315-11ea-a6ae-1c1b0ded7778",
    position_name: "НАЧАЛЬНИК УПРАВЛЕНИЯ",
    position_sort: "6",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "c9231209-48d7-11eb-8110-8030e02da23e",
    staff_iin: "660604300961",
    lastname: "Хаиров",
    firstname: "Аскар",
    patronymic: "Диясович",
    gender: "Мужской",
    birth_date: "04.06.1966",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "429febd8-df71-11ed-8122-8030e02da23e",
    department_name: "Отдел мобилизационной работы ГО и ЧС",
    department_sort: "27",
    position: "1bb05d8c-5315-11ea-a6ae-1c1b0ded7778",
    position_name: "НАЧАЛЬНИК ОТДЕЛА",
    position_sort: "7",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "9cfc6116-984e-11eb-8112-8030e02da23e",
    staff_iin: "930829450281",
    lastname: "Кулакпаева",
    firstname: "Алпеш",
    patronymic: "Сериковна",
    gender: "Женский",
    birth_date: "29.08.1993",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "da6d9a93-1c55-11ec-811a-8030e02da23e",
    department_name: "Управление документационного обеспечения",
    department_sort: "26",
    position: "b6e06477-5313-11ea-a6ae-1c1b0ded7778",
    position_name: "ВЕДУЩИЙ СПЕЦИАЛИСТ",
    position_sort: "9",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "c9a97e42-a359-11eb-8113-8030e02da23e",
    staff_iin: "681129401663",
    lastname: "Кенжалина",
    firstname: "Капия",
    patronymic: "Кадыровна",
    gender: "Женский",
    birth_date: "29.11.1968",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "6a432509-52df-11ea-a6ae-1c1b0ded7778",
    department_name: "Административно-хозяйственный отдел",
    department_sort: "13",
    position: "1bb05d92-5315-11ea-a6ae-1c1b0ded7778",
    position_name: "УБОРЩИК СЛУЖЕБНЫХ ПОМЕЩЕНИЙ",
    position_sort: "13",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "7ad9d167-0429-11ee-8123-8030e02da23e",
    staff_iin: "950805451371",
    lastname: "Акишева",
    firstname: "Сания",
    patronymic: "Карсакбаевна",
    gender: "Женский",
    birth_date: "05.08.1995",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "6a432500-52df-11ea-a6ae-1c1b0ded7778",
    department_name: "Управление государственных закупок",
    department_sort: "15",
    position: "b6e0647b-5313-11ea-a6ae-1c1b0ded7778",
    position_name: "ГЛАВНЫЙ СПЕЦИАЛИСТ",
    position_sort: "8",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "b04b7c87-e39a-11eb-8118-8030e02da23e",
    staff_iin: "840501402010",
    lastname: "Отарова",
    firstname: "Ардак",
    patronymic: "Кенесовна",
    gender: "Женский",
    birth_date: "01.05.1984",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "6a4324fa-52df-11ea-a6ae-1c1b0ded7778",
    department_name:
      "Отдел учета материальных ценностей государственного резерва",
    department_sort: "8",
    position: "1bb05d8c-5315-11ea-a6ae-1c1b0ded7778",
    position_name: "НАЧАЛЬНИК ОТДЕЛА",
    position_sort: "7",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "de86ce4a-e9c4-11ef-8149-8030e02da23e",
    department_name: "Финансово-экономическая служба",
    department_sort: "",
    position: "73a213fc-e9c5-11ef-8149-8030e02da23e",
    position_name: "ФИНАНСОВЫЙ ДИРЕКТОР",
    position_sort: "",
    staff_id: "5cc3235b-93e6-11ea-80fc-8030e02da23d",
    staff_iin: "741031400547",
    lastname: "Кукеева",
    firstname: "Гаухар",
    patronymic: "Амангельдиевна",
    gender: "Женский",
    birth_date: "31.10.1974",
  },
];

// Mock data for staff info
export const MOCK_STAFF_INFO: Array<StaffInfoModel> = [
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "de86ce4a-e9c4-11ef-8149-8030e02da23e",
    department_name: "Финансово-экономическая служба",
    department_sort: "",
    position: "73a213fc-e9c5-11ef-8149-8030e02da23e",
    position_name: "ФИНАНСОВЫЙ ДИРЕКТОР",
    position_sort: "",
    staff_id: "5cc3235b-93e6-11ea-80fc-8030e02da23d",
    hire_date: "15.10.2019",
    staff_iin: "741031400547",
    lastname: "Кукеева",
    firstname: "Гаухар",
    patronymic: "Амангельдиевна",
    gender: "Женский",
    birth_date: "31.10.1974",
    phone: "+77777777",
    mail: "g.kukeyeva@gosrezerv.kz",
    birthplace: "КАЗАХСТАН, Актюбинская область, Мугалжарский район, Ак-Кемир",
    schedule_type: "Пятидневка - 40 часов",
    worker_type: "Штатный сотрудник",
    nationality: "Казахи",
    education: "Магистратура",
    salary: "123,400",
  },
];

// Mock data for staff movements
export const MOCK_STAFF_MOVEMENTS: Array<StaffMovementModel> = [
  {
    position: "НАЧАЛЬНИК УПРАВЛЕНИЯ - ГЛАВНЫЙ БУХГАЛТЕР",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "02.10.2020",
    department: "Управление бухгалтерского учета",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение 274 от 28.09.2020 0:00:00",
  },
  {
    position: "НАЧАЛЬНИК УПРАВЛЕНИЯ - ГЛАВНЫЙ БУХГАЛТЕР",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "01.06.2021",
    department: "Управление бухгалтерского учета",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение оклад от 01.06.2021 0:00:00",
  },
  {
    position: "НАЧАЛЬНИК УПРАВЛЕНИЯ - ГЛАВНЫЙ БУХГАЛТЕР",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "01.01.2022",
    department: "Управление бухгалтерского учета",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение 1 от 01.01.2022 23:59:59",
  },
  {
    position: "НАЧАЛЬНИК УПРАВЛЕНИЯ - ГЛАВНЫЙ БУХГАЛТЕР",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "01.04.2023",
    department: "Управление бухгалтерского учета",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение 00001 от 01.04.2023 13:06:33",
  },
  {
    position: "НАЧАЛЬНИК УПРАВЛЕНИЯ - ГЛАВНЫЙ БУХГАЛТЕР",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "01.01.2024",
    department: "Управление бухгалтерского учета",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение 59/1 от 03.01.2024 17:23:25",
  },
  {
    position: "НАЧАЛЬНИК СЛУЖБЫ",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "13.05.2024",
    department: "Служба бухгалтерского учета - Главный бухгалтер",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение 142 от 13.05.2024 18:53:42",
  },
  {
    position: "НАЧАЛЬНИК СЛУЖБЫ",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "01.07.2024",
    department: "Служба бухгалтерского учета - Главный бухгалтер",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение 216 от 01.07.2024 16:44:34",
  },
  {
    position: "ФИНАНСОВЫЙ ДИРЕКТОР",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "10.02.2025",
    department: "Финансово-экономическая служба",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение 10 от 10.02.2025 10:08:03",
  },
];

// Mock data for staff salaries
export const MOCK_STAFF_SALARIES: StaffSalaryModel[] = [
  {
    position: "ВЕДУЩИЙ СПЕЦИАЛИСТ",
    department: "Коммерческая служба",
    salary_type: "Нет",
    positions_amount: "3",
    salary: "40",
    organization: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВЕДУЩИЙ СПЕЦИАЛИСТ",
    department: "Коммерческая служба",
    salary_type: "Да",
    positions_amount: "3",
    salary: "1005000",
    organization: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВЕДУЩИЙ СПЕЦИАЛИСТ МАТЕРИАЛЬНОГО СКЛАДА (1) УЭО",
    department: "Учетно-экономический отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "3549",
    organization: 'Филиал "Комета" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВЕДУЩИЙ СПЕЦИАЛИСТ МАТЕРИАЛЬНОГО СКЛАДА (1) УЭО",
    department: "Учетно-экономический отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "203000",
    organization: 'Филиал "Комета" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ",
    department: "Административно-хозяйственный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "10",
    organization: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ",
    department: "Административно-хозяйственный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "283000",
    organization: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "6204",
    organization: 'Филиал "Сигнал" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "669844",
    organization: 'Филиал "Автоматика" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "42954",
    organization: 'Филиал "Беркут" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "103759",
    organization: 'Филиал "Комета" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "2",
    salary: "61254",
    organization: 'Филиал "Целина" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "245454",
    organization: 'Филиал "Балхаш" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "6224",
    organization: 'Филиал "Заря" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "183000",
    organization: 'Филиал "Сигнал" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "222000",
    organization: 'Филиал "Автоматика" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "183000",
    organization: 'Филиал "Беркут" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "210000",
    organization: 'Филиал "Комета" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "2",
    salary: "436000",
    organization: 'Филиал "Целина" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "183000",
    organization: 'Филиал "Балхаш" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "183000",
    organization: 'Филиал "Заря" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОПОГРУЗЧИКА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "24697",
    organization: 'Филиал "Автоматика" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОПОГРУЗЧИКА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "195000",
    organization: 'Филиал "Автоматика" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
];
// Mock employee report data
export const MOCK_EMPLOYEE_REPORT: EmployeesReportModel = {
  dropped_out: "",
  dropped_out_year: "",
  hired: "",
  hired_year: "",
  // hired_year: "",
  vacancies: "23",
  vacancies_year: "Х",
  civil_workers: "",
  civil_workers_year: "",
};

export const MOCK_INSTITUTIONS: Array<InstitutionModel> = [
  {
    guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990140003130",
  },
  {
    guid: "36f549c5-683e-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Сигнал" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "060441013160",
  },
  {
    guid: "44c45cd7-6849-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Автоматика" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990141006180",
  },
  {
    guid: "7a3035e7-684f-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Орбита" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990141005965",
  },
  {
    guid: "41b8e67d-6850-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Высота" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990141006051",
  },
  {
    guid: "13e7c5d6-6851-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Беркут" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990241007905",
  },
  {
    guid: "f0e8f13c-6852-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Комета" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990141006100",
  },
  {
    guid: "96c6352b-6853-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Целина" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990141006130",
  },
  {
    guid: "1d140e18-6859-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Стрела" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990241007886",
  },
  {
    guid: "2a367198-6865-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Балхаш" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990241009317",
  },
  {
    guid: "24161cbe-6867-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Заря" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "000141005910",
  },
];

export const MOCK_SALARY_SUMMARY: SalarySummaryModel = {
  accrued_total: "-68",
  accrued: {
    hazard_pay: "24773",
    qualification_bonus: "",
    performance_bonus: "4499820,1",
    vacation_compensation_dismissal: "279844,26",
    taxable_financial_aid: "117960",
    night_shift_pay: "",
    daily_salary: "",
    hourly_salary_amount: "",
    sick_leave_payment: "",
    vacation_payment: "",
    health_allowance_vacation: "",
    holiday_weekend_pay: "",
    bonus_percentage_income: "",
    bonus_fixed_amount: "",
  },
  withheld_total: "8533746,57",
  withheld: {
    medical_insurance_contributions: "787466",
    individual_income_tax: "3 206 808,19",
    mandatory_pension_contributions: "4275903,98",
    union_dues: "",
    other_deductions: "",
    wage_garnishment: "263568,4",
  },
  transferred_total: "45865256,61",
  transferred: {
    bank_transfer: "36368086,68",
  },
  balance_at_end: {
    social_tax: "2521447,24",
    social_contributions: "1879887",
    employer_medical_insurance_contributions: "787466",
    employer_mandatory_pension_contributions: "4275903,98",
  },
};

export const MOCK_MATERIAL_REPORT: Array<MaterialReportModel> = [
  {
    responsible_person: "АШЛЯЕВ РУСЛАН ТЕМИРЖАНОВИЧ",
    total_balance_start_qty: 0,
    balance_start_sum: 0,
    turnover_debit_qty: 0,
    turnover_debit_sum: 0,
    turnover_credit_qty: 0,
    turnover_credit_sum: 0,
    balance_end_qty: 25,
    balance_end_sum: 5507059.68,
    departments: [
      {
        department_name: "Центр оперативного управления",
        total_balance_start_qty: 0,
        balance_start_sum: 0,
        turnover_debit_qty: 0,
        turnover_debit_sum: 0,
        turnover_credit_qty: 0,
        turnover_credit_sum: 0,
        balance_end_qty: 25,
        balance_end_sum: 5507059.68,
        row_number: [
          {
            row_number: "1",
            item_name: "Блок питания Рапан-40",
            nomenclature_number: "241300000096",
            unit: "",
            price: "19 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 19000,
          },
          {
            row_number: "2",
            item_name: "Видеодомофон с электромагнитным ключем",
            nomenclature_number: "241000000216",
            unit: "",
            price: "50 523",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 50523,
          },
          {
            row_number: "3",
            item_name: "Конвертор PERCo АC02 1-01",
            nomenclature_number: "241300000063",
            unit: "",
            price: "29 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 29000,
          },
          {
            row_number: "4",
            item_name: "Металлодетектор рамочный CELA Classic",
            nomenclature_number: "241000000240",
            unit: "",
            price: "429 511",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 429511,
          },
          {
            row_number: "5",
            item_name: "Оборуд. пожарно-охранной сигнализации",
            nomenclature_number: "241000000241",
            unit: "",
            price: "208 184",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 208184,
          },
          {
            row_number: "6",
            item_name: "программное обеспечение Тип 1",
            nomenclature_number: "273000000095",
            unit: "",
            price: "183 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 183000,
          },
          {
            row_number: "7",
            item_name: "программное обеспечение Тип 1",
            nomenclature_number: "273000000096",
            unit: "",
            price: "183 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 183000,
          },
          {
            row_number: "8",
            item_name: "программное обеспечение Тип 1",
            nomenclature_number: "273000000097",
            unit: "",
            price: "183 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 183000,
          },
          {
            row_number: "9",
            item_name: "программное обеспечение Тип 1",
            nomenclature_number: "273000000098",
            unit: "",
            price: "183 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 183000,
          },
          {
            row_number: "10",
            item_name: "программное обеспечение Тип 1",
            nomenclature_number: "273000000099",
            unit: "",
            price: "183 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 183000,
          },
          {
            row_number: "11",
            item_name: "программное обеспечение Тип 2",
            nomenclature_number: "273000000100",
            unit: "",
            price: "186 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 186000,
          },
          {
            row_number: "12",
            item_name: "программное обеспечение Тип 2",
            nomenclature_number: "273000000101",
            unit: "",
            price: "186 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 186000,
          },
          {
            row_number: "13",
            item_name: "программное обеспечение Тип 2",
            nomenclature_number: "273000000102",
            unit: "",
            price: "186 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 186000,
          },
          {
            row_number: "14",
            item_name: "программное обеспечение Тип 2",
            nomenclature_number: "273000000103",
            unit: "",
            price: "186 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 186000,
          },
          {
            row_number: "15",
            item_name: "программное обеспечение Тип 2",
            nomenclature_number: "273000000104",
            unit: "",
            price: "186 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 186000,
          },
          {
            row_number: "16",
            item_name: "программное обеспечение Тип 3",
            nomenclature_number: "273000000105",
            unit: "",
            price: "145 200",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 145200,
          },
          {
            row_number: "17",
            item_name: "программное обеспечение Тип 3",
            nomenclature_number: "273000000106",
            unit: "",
            price: "145 200",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 145200,
          },
          {
            row_number: "18",
            item_name: "программное обеспечение Тип 3",
            nomenclature_number: "273000000107",
            unit: "",
            price: "145 200",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 145200,
          },
          {
            row_number: "19",
            item_name: "программное обеспечение Тип 3",
            nomenclature_number: "273000000108",
            unit: "",
            price: "145 200",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 145200,
          },
          {
            row_number: "20",
            item_name: "программное обеспечение Тип 3",
            nomenclature_number: "273000000109",
            unit: "",
            price: "145 200",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 145200,
          },
          {
            row_number: "21",
            item_name: "Система контроля и управления доступом",
            nomenclature_number: "241000000246",
            unit: "",
            price: "789 012",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 789012,
          },
          {
            row_number: "22",
            item_name: "Система охранной сигнализации",
            nomenclature_number: "241000000247",
            unit: "",
            price: "557 829,68",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 557829.68,
          },
          {
            row_number: "23",
            item_name: "телефон сотовой связи ",
            nomenclature_number: "241300003353",
            unit: "",
            price: "97 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 97000,
          },
          {
            row_number: "24",
            item_name: "Терминал распознавания лица Hikvision DS-K1T671M",
            nomenclature_number: "241300000074",
            unit: "",
            price: "378 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 378000,
          },
          {
            row_number: "25",
            item_name: "Терминал распознавания лица Hikvision DS-K1T671M",
            nomenclature_number: "241300000075",
            unit: "",
            price: "378 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 378000,
          },
        ],
      },
    ],
  },
  {
    responsible_person: "Бозжигитов Бауржан Жексембаевич",
    total_balance_start_qty: 5,
    balance_start_sum: 2035059.68,
    turnover_debit_qty: 0,
    turnover_debit_sum: 0,
    turnover_credit_qty: 0,
    turnover_credit_sum: 0,
    balance_end_qty: 0,
    balance_end_sum: 0,
    departments: [
      {
        department_name: "Центр оперативного управления",
        total_balance_start_qty: 5,
        balance_start_sum: 2035059.68,
        turnover_debit_qty: 0,
        turnover_debit_sum: 0,
        turnover_credit_qty: 0,
        turnover_credit_sum: 0,
        balance_end_qty: 0,
        balance_end_sum: 0,
        row_number: [
          {
            row_number: "26",
            item_name: "Видеодомофон с электромагнитным ключем",
            nomenclature_number: "241000000216",
            unit: "",
            price: "50 523",
            total_balance_start_qty: 1,
            balance_start_sum: 50523,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 0,
            balance_end_sum: 0,
          },
          {
            row_number: "27",
            item_name: "Металлодетектор рамочный CELA Classic",
            nomenclature_number: "241000000240",
            unit: "",
            price: "429 511",
            total_balance_start_qty: 1,
            balance_start_sum: 429511,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 0,
            balance_end_sum: 0,
          },
          {
            row_number: "28",
            item_name: "Оборуд. пожарно-охранной сигнализации",
            nomenclature_number: "241000000241",
            unit: "",
            price: "208 184",
            total_balance_start_qty: 1,
            balance_start_sum: 208184,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 0,
            balance_end_sum: 0,
          },
          {
            row_number: "29",
            item_name: "Система контроля и управления доступом",
            nomenclature_number: "241000000246",
            unit: "",
            price: "789 012",
            total_balance_start_qty: 1,
            balance_start_sum: 789012,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 0,
            balance_end_sum: 0,
          },
          {
            row_number: "30",
            item_name: "Система охранной сигнализации",
            nomenclature_number: "241000000247",
            unit: "",
            price: "557 829,68",
            total_balance_start_qty: 1,
            balance_start_sum: 557829.68,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 0,
            balance_end_sum: 0,
          },
        ],
      },
    ],
  },
  {
    responsible_person: "Кошеков Нурлан Самарбекович",
    total_balance_start_qty: 0,
    balance_start_sum: 0,
    turnover_debit_qty: 1,
    turnover_debit_sum: 97000,
    turnover_credit_qty: 0,
    turnover_credit_sum: 0,
    balance_end_qty: 0,
    balance_end_sum: 0,
    departments: [
      {
        department_name: "Центр оперативного управления",
        total_balance_start_qty: 0,
        balance_start_sum: 0,
        turnover_debit_qty: 1,
        turnover_debit_sum: 97000,
        turnover_credit_qty: 0,
        turnover_credit_sum: 0,
        balance_end_qty: 0,
        balance_end_sum: 0,
        row_number: [
          {
            row_number: "958",
            item_name: "телефон сотовой связи ",
            nomenclature_number: "241300003353",
            unit: "",
            price: "97 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 1,
            turnover_debit_sum: 97000,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 0,
            balance_end_sum: 0,
          },
        ],
      },
    ],
  },
];

export const MOCK_ASSETS: {
  data: Array<AssetsModel>;
  report_date: string;
} = {
  data: [
    {
      code: "010",
      description: "Денежные средства и их эквиваленты",
      start_period_value: "218994215,98",
      end_period_value: "559766880,25",
    },
    {
      code: "011",
      description:
        "Краткосрочные финансовые активы, оцениваемые по амортизированной стоимости",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "012",
      description:
        "Краткосрочные финансовые активы, оцениваемые по справедливой стоимости через прочий совокупный доход",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "013",
      description:
        "Краткосрочные финансовые активы, учитываемые по справедливой стоимости через прибыли или убытки",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "014",
      description: "Краткосрочные производные финансовые инструменты",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "015",
      description: "Прочие краткосрочные финансовые активы",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "016",
      description: "Краткосрочная торговая и прочая дебиторская задолженность",
      start_period_value: "23776128,15",
      end_period_value: "3162960,07",
    },
    {
      code: "017",
      description: "Краткосрочная дебиторская задолженность по аренде",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "018",
      description: "Краткосрочные активы по договорам с покупателями",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "019",
      description: "Текущий подоходный налог",
      start_period_value: "71640057,77",
      end_period_value: "71640057,77",
    },
    {
      code: "020",
      description: "Запасы",
      start_period_value: "75047642,43",
      end_period_value: "12620333,31",
    },
    {
      code: "021",
      description: "Биологические активы",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "022",
      description: "Прочие краткосрочные активы",
      start_period_value: "372197952,36",
      end_period_value: "118192874,62",
    },
    {
      code: "110",
      description:
        "Долгосрочные финансовые активы, оцениваемые по амортизированной стоимости",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "111",
      description:
        "Долгосрочные финансовые активы, оцениваемые по справедливой стоимости через прочий совокупный доход",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "112",
      description:
        "Долгосрочные финансовые активы, учитываемые по справедливой стоимости через прибыли или убытки",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "113",
      description: "Долгосрочные производные финансовые инструменты",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "114",
      description: "Инвестиции, учитываемые по первоначальной стоимости",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "115",
      description: "Инвестиции, учитываемые методом долевого участия",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "116",
      description: "Прочие долгосрочные финансовые активы",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "117",
      description: "Долгосрочная торговая и прочая дебиторская задолженность",
      start_period_value: "-744693",
      end_period_value: "",
    },
    {
      code: "118",
      description: "Долгосрочная дебиторская задолженность по аренде",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "119",
      description: "Долгосрочные активы по договорам с покупателями",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "120",
      description: "Инвестиционное имущество",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "121",
      description: "Основные средства",
      start_period_value: "607638847,55",
      end_period_value: "258403810,09",
    },
    {
      code: "122",
      description: "Актив в форме права пользования",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "123",
      description: "Биологические активы",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "124",
      description: "Разведочные и оценочные активы",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "125",
      description: "Нематериальные активы",
      start_period_value: "25502706,6",
      end_period_value: "30299335,04",
    },
    {
      code: "126",
      description: "Отложенные налоговые активы",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "127",
      description: "Прочие долгосрочные активы",
      start_period_value: "97226772,06",
      end_period_value: "97226772,06",
    },
    {
      code: "210",
      description:
        "Краткосрочные финансовые обязательства, оцениваемые по амортизированной стоимости",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "211",
      description:
        "Краткосрочные финансовые обязательства, оцениваемые по справедливой стоимости через прибыль или убыток",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "212",
      description: "Краткосрочные производные финансовые инструменты",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "213",
      description: "Прочие краткосрочные финансовые обязательства",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "214",
      description: "Краткосрочная торговая и прочая кредиторская задолженность",
      start_period_value: "234363617,1",
      end_period_value: "14130406,7",
    },
    {
      code: "215",
      description: "Краткосрочные оценочные обязательства",
      start_period_value: "37985282,57",
      end_period_value: "28679703,86",
    },
    {
      code: "216",
      description: "Текущие налоговые обязательства по подоходному налогу",
      start_period_value: "32570733",
      end_period_value: "32570733",
    },
    {
      code: "217",
      description: "Вознаграждения работникам",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "218",
      description: "Краткосрочная задолженность по аренде",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "219",
      description: "Краткосрочные обязательства по договорам покупателями",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "222",
      description: "Прочие краткосрочные обязательства",
      start_period_value: "168390449,25",
      end_period_value: "0,02",
    },
    {
      code: "301",
      description:
        "Обязательства выбывающих групп, предназначенных для продажи",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "310",
      description:
        "Долгосрочные финансовые обязательства, оцениваемые по амортизированной стоимости",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "311",
      description:
        "Долгосрочные финансовые обязательства, оцениваемые по справедливой стоимости через прибыль или убыток",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "312",
      description: "Долгосрочные производные финансовые инструменты",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "313",
      description: "Прочие долгосрочные финансовые обязательства",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "314",
      description: "Долгосрочная торговая и прочая кредиторская задолженность",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "315",
      description: "Долгосрочные оценочные обязательства",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "316",
      description: "Отложенные налоговые обязательства",
      start_period_value: "334096260,61",
      end_period_value: "334096260,61",
    },
    {
      code: "317",
      description: "Вознаграждения работникам",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "318",
      description: "Долгосрочная задолженность по аренде",
      start_period_value: "563380216,42",
      end_period_value: "",
    },
    {
      code: "319",
      description: "Долгосрочные обязательства по договорам с покупателями",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "321",
      description: "Прочие долгосрочные обязательства",
      start_period_value: "98291778,2",
      end_period_value: "214386053,5",
    },
    {
      code: "410",
      description: "Уставный (акционерный) капитал",
      start_period_value: "1793111191,02",
      end_period_value: "1793111191,02",
    },
    {
      code: "411",
      description: "Эмиссионный доход",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "412",
      description: "Выкупленные собственные долевые инструменты",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "413",
      description: "Компоненты прочего совокупного дохода",
      start_period_value: "1634329,12",
      end_period_value: "1634329,12",
    },
    {
      code: "414",
      description: "Нераспределенная прибыль (непокрытый убыток)",
      start_period_value: "-1772544227,39",
      end_period_value: "-1267295654,62",
    },
    {
      code: "415",
      description: "Прочий капитал",
      start_period_value: "",
      end_period_value: "",
    },
  ],
  report_date: "12.06.2025",
};

export const MOCK_TURNOVER_BALANCE: {
  data: Array<TurnoverBalanceModel>;
  metadata: {
    total_records: string;
    export_format: string;
  };
} = {
  data: [
    {
      account: "1312. ",
      mol: "Нургалиев Ербол Кыдырбекович",
      nomenclature: "Талоны Бензин Аи-92+",
      balance_start_debit: "8678,05",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "8678,05",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1312. ",
      mol: "Амиржанов Алмаз Куспанович",
      nomenclature: "Бензин Аи-95-К4",
      balance_start_debit: "3,28",
      balance_start_credit: "",
      turnover_debit: "155800",
      turnover_credit: "155803,28",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1312. ",
      mol: "Амиржанов Алмаз Куспанович",
      nomenclature: "Бензин Аи -95",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "499500",
      turnover_credit: "499500",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1312. ",
      mol: "МУХАМЕДЖАНОВ САЯТ БОГЕНБАЕВИЧ",
      nomenclature: "Бензин Аи -95",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "217500",
      turnover_credit: "87500",
      balance_end_debit: "130000",
      balance_end_credit: "",
    },
    {
      account: "1312. ",
      mol: "МУХАМЕДЖАНОВ САЯТ БОГЕНБАЕВИЧ",
      nomenclature: "Бензин Аи -95",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "351000",
      turnover_credit: "350991,9",
      balance_end_debit: "8,1",
      balance_end_credit: "",
    },
    {
      account: "1312. ",
      mol: "Нурбосынов Бахытжан Сулейменович",
      nomenclature: "Бензин Аи-92",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "31116,07",
      turnover_credit: "",
      balance_end_debit: "31116,07",
      balance_end_credit: "",
    },
    {
      account: "1312. ",
      mol: "Нурбосынов Бахытжан Сулейменович",
      nomenclature: "Талоны Бензин Аи-92+",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "8678,05",
      turnover_credit: "",
      balance_end_debit: "8678,05",
      balance_end_credit: "",
    },
    {
      account: "1312. ",
      mol: "Нурбосынов Бахытжан Сулейменович",
      nomenclature: "Бензин Аи -95",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "375000",
      turnover_credit: "217500",
      balance_end_debit: "157500",
      balance_end_credit: "",
    },
    {
      account: "1312. ",
      mol: "Нурбосынов Бахытжан Сулейменович",
      nomenclature: "Бензин Аи-95-К4",
      balance_start_debit: "155800",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "155800",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1312. ",
      mol: "Нурбосынов Бахытжан Сулейменович",
      nomenclature: "Бензин Аи-92+",
      balance_start_debit: "39960",
      balance_start_credit: "",
      turnover_debit: "1295000",
      turnover_credit: "1334960",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1312. ",
      mol: "Нурбосынов Бахытжан Сулейменович",
      nomenclature: "Дизельное топливо зимнее+",
      balance_start_debit: "11607",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "11607",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1312. ",
      mol: "Нурбосынов Бахытжан Сулейменович",
      nomenclature: "Бензин Аи -95",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "850500",
      turnover_credit: "850500",
      balance_end_debit: "",
      balance_end_credit: "",
    },
  ],
  metadata: {
    total_records: "12",
    export_format: "json",
  },
};

export const MOCK_TURNOVER_BALANCE_2: {
  data: Array<TurnoverBalanceModel>;
  metadata: {
    total_records: string;
    export_format: string;
  };
} = {
  data: [
    {
      account: "1030. ",
      mol: "",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "23200",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "",
      balance_end_debit: "1208",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "",
      nomenclature: "KZ00418540/19 РБ ЦА Народный банк,  Овернайт 15 %",
      balance_start_debit: "300000000",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "",
      balance_end_debit: "100000000",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "",
      nomenclature: "KZ9094805KZT22033717  Обеспечение договора",
      balance_start_debit: "6692199,55",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "",
      balance_end_debit: "22755560,22",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "",
      nomenclature: "KZ288562215131368976 БЦК",
      balance_start_debit: "200000000",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "",
      nomenclature: 'KZ4394805KZT22151157, Депозит "Евразийский банк" 14.55%',
      balance_start_debit: "53051480,7",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "",
      nomenclature: "KZ718562215139120248 БЦК 14 %",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "",
      balance_end_debit: "100000000",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "",
      nomenclature: 'KZ2694805KZT22151560 Депозит "Евразийский банк" 13.70%',
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "",
      balance_end_debit: "9929715,68",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Расчеты по ОПВ",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "303797940,22",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Социальный налог ",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "179211564,48",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат зарплаты",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "32565217,97",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Налог на имущество",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "24900477",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Земельный налог",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "30303016,08",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Налог на транспорт",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "3038501",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "За загрязнение окружающей среды",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "2073754",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Гос.пошлина",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "910822,06",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат  от поставщика ",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "99698,88",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат  от поставщика ",
      nomenclature: "KZ9094805KZT22033717  Обеспечение договора",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "207199",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат ОПВ",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "1301389,78",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат ОСМС",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "223328",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат СО",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "66550",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат ВОСМС",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "247954",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами ",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "8759354324,73",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами ",
      nomenclature: "KZ00418540/19 РБ ЦА Народный банк,  Овернайт 15 %",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "14159999530",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами ",
      nomenclature: "KZ9094805KZT22033717  Обеспечение договора",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "43255303,87",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами ",
      nomenclature: "KZ148562203117459933 БЦК",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "1621543664,38",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами ",
      nomenclature: "KZ288562215131368976 БЦК",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "150000000",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами ",
      nomenclature: 'KZ4394805KZT22151157, Депозит "Евразийский банк" 14.55%',
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "1177400471,05",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами ",
      nomenclature: 'KZ0794805KZT22151320 Депозит "Евразийский банк" 13.90%',
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "890061149,09",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами ",
      nomenclature: 'KZ6094805KZT22151433 Депозит "Евразийский банк" 13.70%',
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "2216122213,53",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами ",
      nomenclature: "KZ718562215139120248 БЦК 14 %",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "600000000",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами ",
      nomenclature: 'KZ2694805KZT22151560 Депозит "Евразийский банк" 13.70%',
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "2652924100,12",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами ",
      nomenclature: "KZ746017111000000108 РБ ЦА Народный банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "880001880,86",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Вклад  выплат по Овернайт ",
      nomenclature: "KZ746017111000000108 РБ ЦА Народный банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "14359999530",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Вклад по депозиту Овернайт ",
      nomenclature: "KZ746017111000000108 РБ ЦА Народный банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "11559999530",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Проф взносы",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "13297558,78",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Налог на добычу полезных ископаемых",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "313022",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат командировочных расходов",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "2091688",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Плата за использ. радиочаст. спектра ",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "92300",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат платежей поставщикам за товары и услуги",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "369438,39",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат  по исполнительным листам ",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "1061199,28",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат  по исполнительным листам ",
      nomenclature: "KZ9094805KZT22033717  Обеспечение договора",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "34608",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Поступление  пени от поставщиков по Договорам ",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "4437,49",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Поступление  пени от поставщиков по Договорам ",
      nomenclature: "KZ9094805KZT22033717  Обеспечение договора",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "782083,84",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Налог на добавленную стоимость",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "294640000",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Пеня по  ООСМС",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "1177",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Пеня по ОПВ",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "5408,92",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Пеня по ВОСМС",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "750",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Доходы от поклажедателей",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "144500",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Доходы от поклажедателей",
      nomenclature: "KZ9094805KZT22033717  Обеспечение договора",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "1123178260,31",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат неустойки ",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "175181",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат госпошлины",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "213471,45",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат госпошлины",
      nomenclature: "KZ9094805KZT22033717  Обеспечение договора",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "3450",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат платежей поклажедателям",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "25150",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "7240032843,36",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами",
      nomenclature: "KZ9094805KZT22033717  Обеспечение договора",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "1167346763,19",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами",
      nomenclature: "KZ148562203117459933 БЦК",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "1621543664,38",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами",
      nomenclature: "KZ288562215131368976 БЦК",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "360774167,82",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами",
      nomenclature: 'KZ4394805KZT22151157, Депозит "Евразийский банк" 14.55%',
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "1230451951,75",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами",
      nomenclature: 'KZ0794805KZT22151320 Депозит "Евразийский банк" 13.90%',
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "890061149,09",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами",
      nomenclature: 'KZ6094805KZT22151433 Депозит "Евразийский банк" 13.70%',
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "2216122213,53",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами",
      nomenclature: "KZ718562215139120248 БЦК 14 %",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "510869496,56",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами",
      nomenclature: 'KZ2694805KZT22151560 Депозит "Евразийский банк" 13.70%',
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "2642994384,44",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Перевод между банковскими счетами",
      nomenclature: "KZ746017111000000108 РБ ЦА Народный банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "3710466473,51",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Приобретение основных средств",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "152094757,49",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Прочие выплаты от инвестиционной деятельности",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "25003000",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Выплаты по оплате труда",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "2715650051,54",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Корпоративный подоходный налог",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "1255742,67",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Платежи поставщикам за товары и услуги",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "2192206908,12",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Платежи поставщикам за товары и услуги",
      nomenclature: "KZ9094805KZT22033717  Обеспечение договора",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "136007,16",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Платежи поставщикам за товары и услуги",
      nomenclature: "KZ746017111000000108 РБ ЦА Народный банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "5500",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Подоходный налог и другие платежи в бюджет",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "242626274,07",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Прочие выплаты от операционной деятельности",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "105000000",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Выплата вознаграждения",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "14263071,28",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Полученные вознаграждения",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "31119921,97",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Полученные вознаграждения",
      nomenclature: "KZ288562215131368976 БЦК",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "10774167,82",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Полученные вознаграждения",
      nomenclature: "KZ718562215139120248 БЦК 14 %",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "10869496,56",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Полученные вознаграждения",
      nomenclature: "KZ746017111000000108 РБ ЦА Народный банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "30481943,51",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Поступления от реализации товаров и услуг",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "5033179299,37",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Прочие поступления от операционной деятельности",
      nomenclature: "KZ00418540/19 РБ ЦА Народный банк,  Овернайт 15 %",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "14359999530",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Командировочные расходы",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "59005705,28",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Банковские услуги",
      nomenclature: "KZ746017111000000108 РБ ЦА Народный банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "11850,86",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Возврат гарантийных взносов",
      nomenclature: "KZ9094805KZT22033717  Обеспечение договора",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "18040474",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Расчеты с ООСМС",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "72264190",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Расчеты с ВОСМС",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "49455463",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Расчеты с СО",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "80840172",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Поступление гарантийных взносов",
      nomenclature: "KZ9094805KZT22033717  Обеспечение договора",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "34125700",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Расчеты по исполнительным листам",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "24440036,85",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Расчеты по решению суда, штрафы, пени",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "",
      turnover_credit: "34494025,77",
      balance_end_debit: "",
      balance_end_credit: "",
    },
    {
      account: "1030. ",
      mol: "Расчеты по решению суда, штрафы, пени",
      nomenclature: "KZ2494805KZT22033644 Внебюджет ЦА, Евразийский банк",
      balance_start_debit: "",
      balance_start_credit: "",
      turnover_debit: "93329,44",
      turnover_credit: "",
      balance_end_debit: "",
      balance_end_credit: "",
    },
  ],
  metadata: {
    total_records: "89",
    export_format: "json",
  },
};

export const MOCK_AWARDS: {
  awards: Array<AwardsModel>;
  employeeGuid: string;
  description: string;
  result: boolean;
} = {
  result: true,
  description: "",
  employeeGuid: "5cc3235b-93e6-11ea-80fc-8030e02da23d",
  awards: [
    {
      date: "13.12.2021",
      person: "Кукеева Гаухар Амангельдиевна",
      awardType: "Почетная грамота РГП Резерв",
      awardCategory: "Почетная",
      orderNumber: "282",
      reason: "За хорошие достижения",
    },
    {
      date: "03.03.2022",
      person: "Кукеева Гаухар Амангельдиевна",
      awardType: "Грамота Министра МЧС РК",
      awardCategory: "Ведомственная",
      orderNumber: "№ 59 л/с",
      reason:
        "к 8 марта 2022 и за добросовестное исполнение служебных обязанностей",
    },
  ],
};

export const MOCK_DISCIPLINARY: {
  disciplinaryActions: Array<DisciplinaryModel>;
  employeeGuid: string;
  description: string;
  result: boolean;
} = {
  result: true,
  description: "",
  employeeGuid: "5cc3235b-93e6-11ea-80fc-8030e02da23d",
  disciplinaryActions: [
    {
      datePeriod: "29.09.2022",
      registrar: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
      institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
      penaltyType: "Замечание",
      reason: "В соответствии с пп1) пунктом 1 статьи 64 ТК РК",
      action: "",
      department: "Управление бухгалтерского учета",
      imposedBy: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    },
    {
      datePeriod: "18.10.2022",
      registrar: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
      institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
      penaltyType: "Замечание",
      reason: "",
      action: "",
      department: "Управление бухгалтерского учета",
      imposedBy: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    },
    {
      datePeriod: "28.03.2023",
      registrar: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
      institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
      penaltyType: "Замечание",
      reason: "",
      action: "",
      department: "Управление бухгалтерского учета",
      imposedBy: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    },
  ],
};
