import {
  AssetsModel,
  EmployeesReportModel,
  InstitutionModel,
  MaterialReportModel,
  SalarySummaryModel,
  StaffInfoModel,
  StaffModel,
  StaffMovementModel,
  StaffSalaryModel,
} from "@/lib/api-service";

// Mock data for testing
export const MOCK_STAFF_DATA: Array<StaffModel> = [
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "663fd553-311d-11ee-8123-8030e02da23e",
    staff_iin: "711105300864",
    lastname: "САЛИМБАЕВ",
    firstname: "ЖАНАТ",
    patronymic: "САКЫТАЕВИЧ",
    gender: "Мужской",
    birth_date: "05.11.1971",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "6a4324f5-52df-11ea-a6ae-1c1b0ded7778",
    department_name: "Административно-управленческий персонал",
    department_sort: "1",
    position: "29652026-b896-11eb-8115-8030e02da23e",
    position_name: "СОВЕТНИК-КОМПЛАЕНС ОФИЦЕР",
    position_sort: "4",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "7530343f-cb2e-11ef-8147-8030e02da23e",
    staff_iin: "870313400503",
    lastname: "Уталиева",
    firstname: "Лунара",
    patronymic: "Курманбековна",
    gender: "Женский",
    birth_date: "13.03.1987",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "6a4324f9-52df-11ea-a6ae-1c1b0ded7778",
    department_name: "Отдел технологического обеспечения",
    department_sort: "7",
    position: "b6e0647b-5313-11ea-a6ae-1c1b0ded7778",
    position_name: "ГЛАВНЫЙ СПЕЦИАЛИСТ",
    position_sort: "8",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "fc6c785d-e763-11ea-810a-8030e02da23e",
    staff_iin: "750414350082",
    lastname: "Молдаханов",
    firstname: "Бекет",
    patronymic: "Кадырбекович",
    gender: "Мужской",
    birth_date: "14.04.1975",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "935f8164-129c-11ef-8134-8030e02da23e",
    department_name: "Управление активами",
    department_sort: "11",
    position: "1bb05d8d-5315-11ea-a6ae-1c1b0ded7778",
    position_name: "НАЧАЛЬНИК УПРАВЛЕНИЯ",
    position_sort: "6",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "e15fcf10-f356-11ea-810b-8030e02da23e",
    staff_iin: "860308403310",
    lastname: "ДЮСЕБАЕВА",
    firstname: "МАДИНА",
    patronymic: "КАРАКУЛОВНА",
    gender: "Женский",
    birth_date: "08.03.1986",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "26583111-a44e-11ea-8104-8030e02da23e",
    department_name: "Отдел сопровождения проектов",
    department_sort: "12",
    position: "1bb05d8c-5315-11ea-a6ae-1c1b0ded7778",
    position_name: "НАЧАЛЬНИК ОТДЕЛА",
    position_sort: "7",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "540bfc48-3b8e-11eb-8110-8030e02da23e",
    staff_iin: "630126301510",
    lastname: "Машрапов",
    firstname: "Оралбек",
    patronymic: "Солтанович",
    gender: "Мужской",
    birth_date: "26.01.1963",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "6a4324fd-52df-11ea-a6ae-1c1b0ded7778",
    department_name: "Управление материально-технического обеспечения",
    department_sort: "9",
    position: "1bb05d8d-5315-11ea-a6ae-1c1b0ded7778",
    position_name: "НАЧАЛЬНИК УПРАВЛЕНИЯ",
    position_sort: "6",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "c9231209-48d7-11eb-8110-8030e02da23e",
    staff_iin: "660604300961",
    lastname: "Хаиров",
    firstname: "Аскар",
    patronymic: "Диясович",
    gender: "Мужской",
    birth_date: "04.06.1966",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "429febd8-df71-11ed-8122-8030e02da23e",
    department_name: "Отдел мобилизационной работы ГО и ЧС",
    department_sort: "27",
    position: "1bb05d8c-5315-11ea-a6ae-1c1b0ded7778",
    position_name: "НАЧАЛЬНИК ОТДЕЛА",
    position_sort: "7",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "9cfc6116-984e-11eb-8112-8030e02da23e",
    staff_iin: "930829450281",
    lastname: "Кулакпаева",
    firstname: "Алпеш",
    patronymic: "Сериковна",
    gender: "Женский",
    birth_date: "29.08.1993",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "da6d9a93-1c55-11ec-811a-8030e02da23e",
    department_name: "Управление документационного обеспечения",
    department_sort: "26",
    position: "b6e06477-5313-11ea-a6ae-1c1b0ded7778",
    position_name: "ВЕДУЩИЙ СПЕЦИАЛИСТ",
    position_sort: "9",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "c9a97e42-a359-11eb-8113-8030e02da23e",
    staff_iin: "681129401663",
    lastname: "Кенжалина",
    firstname: "Капия",
    patronymic: "Кадыровна",
    gender: "Женский",
    birth_date: "29.11.1968",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "6a432509-52df-11ea-a6ae-1c1b0ded7778",
    department_name: "Административно-хозяйственный отдел",
    department_sort: "13",
    position: "1bb05d92-5315-11ea-a6ae-1c1b0ded7778",
    position_name: "УБОРЩИК СЛУЖЕБНЫХ ПОМЕЩЕНИЙ",
    position_sort: "13",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "7ad9d167-0429-11ee-8123-8030e02da23e",
    staff_iin: "950805451371",
    lastname: "Акишева",
    firstname: "Сания",
    patronymic: "Карсакбаевна",
    gender: "Женский",
    birth_date: "05.08.1995",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "6a432500-52df-11ea-a6ae-1c1b0ded7778",
    department_name: "Управление государственных закупок",
    department_sort: "15",
    position: "b6e0647b-5313-11ea-a6ae-1c1b0ded7778",
    position_name: "ГЛАВНЫЙ СПЕЦИАЛИСТ",
    position_sort: "8",
  },
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    staff_id: "b04b7c87-e39a-11eb-8118-8030e02da23e",
    staff_iin: "840501402010",
    lastname: "Отарова",
    firstname: "Ардак",
    patronymic: "Кенесовна",
    gender: "Женский",
    birth_date: "01.05.1984",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "6a4324fa-52df-11ea-a6ae-1c1b0ded7778",
    department_name:
      "Отдел учета материальных ценностей государственного резерва",
    department_sort: "8",
    position: "1bb05d8c-5315-11ea-a6ae-1c1b0ded7778",
    position_name: "НАЧАЛЬНИК ОТДЕЛА",
    position_sort: "7",
  },
];

// Mock data for staff info
export const MOCK_STAFF_INFO: Array<StaffInfoModel> = [
  {
    institution_guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    institution_name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    institution_bin: "990140003130",
    struct_guid: "00000000-0000-0000-0000-000000000000",
    struct_name: "",
    struct_bin: "",
    department_guid: "de86ce4a-e9c4-11ef-8149-8030e02da23e",
    department_name: "Финансово-экономическая служба",
    department_sort: "",
    position: "73a213fc-e9c5-11ef-8149-8030e02da23e",
    position_name: "ФИНАНСОВЫЙ ДИРЕКТОР",
    position_sort: "",
    staff_id: "5cc3235b-93e6-11ea-80fc-8030e02da23d",
    hire_date: "15.10.2019",
    staff_iin: "741031400547",
    lastname: "Кукеева",
    firstname: "Гаухар",
    patronymic: "Амангельдиевна",
    gender: "Женский",
    birth_date: "31.10.1974",
    phone: "+77777777",
    mail: "g.kukeyeva@gosrezerv.kz",
    birthplace: "КАЗАХСТАН, Актюбинская область, Мугалжарский район, Ак-Кемир",
    schedule_type: "Пятидневка - 40 часов",
    worker_type: "Штатный сотрудник",
    nationality: "Казахи",
    education: "Магистратура",
    salary: "123,400",
  },
];

// Mock data for staff movements
export const MOCK_STAFF_MOVEMENTS: Array<StaffMovementModel> = [
  {
    position: "НАЧАЛЬНИК УПРАВЛЕНИЯ - ГЛАВНЫЙ БУХГАЛТЕР",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "02.10.2020",
    department: "Управление бухгалтерского учета",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение 274 от 28.09.2020 0:00:00",
  },
  {
    position: "НАЧАЛЬНИК УПРАВЛЕНИЯ - ГЛАВНЫЙ БУХГАЛТЕР",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "01.06.2021",
    department: "Управление бухгалтерского учета",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение оклад от 01.06.2021 0:00:00",
  },
  {
    position: "НАЧАЛЬНИК УПРАВЛЕНИЯ - ГЛАВНЫЙ БУХГАЛТЕР",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "01.01.2022",
    department: "Управление бухгалтерского учета",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение 1 от 01.01.2022 23:59:59",
  },
  {
    position: "НАЧАЛЬНИК УПРАВЛЕНИЯ - ГЛАВНЫЙ БУХГАЛТЕР",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "01.04.2023",
    department: "Управление бухгалтерского учета",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение 00001 от 01.04.2023 13:06:33",
  },
  {
    position: "НАЧАЛЬНИК УПРАВЛЕНИЯ - ГЛАВНЫЙ БУХГАЛТЕР",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "01.01.2024",
    department: "Управление бухгалтерского учета",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение 59/1 от 03.01.2024 17:23:25",
  },
  {
    position: "НАЧАЛЬНИК СЛУЖБЫ",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "13.05.2024",
    department: "Служба бухгалтерского учета - Главный бухгалтер",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение 142 от 13.05.2024 18:53:42",
  },
  {
    position: "НАЧАЛЬНИК СЛУЖБЫ",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "01.07.2024",
    department: "Служба бухгалтерского учета - Главный бухгалтер",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение 216 от 01.07.2024 16:44:34",
  },
  {
    position: "ФИНАНСОВЫЙ ДИРЕКТОР",
    institution: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    date: "10.02.2025",
    department: "Финансово-экономическая служба",
    worker_type: "Штатный сотрудник",
    event: "",
    document: "Кадровое перемещение 10 от 10.02.2025 10:08:03",
  },
];

// Mock data for staff salaries
export const MOCK_STAFF_SALARIES: StaffSalaryModel[] = [
  {
    position: "ВЕДУЩИЙ СПЕЦИАЛИСТ",
    department: "Коммерческая служба",
    salary_type: "Нет",
    positions_amount: "3",
    salary: "40",
    organization: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВЕДУЩИЙ СПЕЦИАЛИСТ",
    department: "Коммерческая служба",
    salary_type: "Да",
    positions_amount: "3",
    salary: "1005000",
    organization: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВЕДУЩИЙ СПЕЦИАЛИСТ МАТЕРИАЛЬНОГО СКЛАДА (1) УЭО",
    department: "Учетно-экономический отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "3549",
    organization: 'Филиал "Комета" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВЕДУЩИЙ СПЕЦИАЛИСТ МАТЕРИАЛЬНОГО СКЛАДА (1) УЭО",
    department: "Учетно-экономический отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "203000",
    organization: 'Филиал "Комета" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ",
    department: "Административно-хозяйственный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "10",
    organization: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ",
    department: "Административно-хозяйственный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "283000",
    organization: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "6204",
    organization: 'Филиал "Сигнал" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "669844",
    organization: 'Филиал "Автоматика" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "42954",
    organization: 'Филиал "Беркут" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "103759",
    organization: 'Филиал "Комета" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "2",
    salary: "61254",
    organization: 'Филиал "Целина" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "245454",
    organization: 'Филиал "Балхаш" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "6224",
    organization: 'Филиал "Заря" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "183000",
    organization: 'Филиал "Сигнал" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "222000",
    organization: 'Филиал "Автоматика" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "183000",
    organization: 'Филиал "Беркут" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "210000",
    organization: 'Филиал "Комета" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "2",
    salary: "436000",
    organization: 'Филиал "Целина" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "183000",
    organization: 'Филиал "Балхаш" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОБУСА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "183000",
    organization: 'Филиал "Заря" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОПОГРУЗЧИКА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Нет",
    positions_amount: "1",
    salary: "24697",
    organization: 'Филиал "Автоматика" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
  {
    position: "ВОДИТЕЛЬ АВТОПОГРУЗЧИКА",
    department: "Производственно-эксплуатационный отдел",
    salary_type: "Да",
    positions_amount: "1",
    salary: "195000",
    organization: 'Филиал "Автоматика" РГП на ПХВ "Резерв" КГМР МЧС РК',
  },
];
// Mock employee report data
export const MOCK_EMPLOYEE_REPORT: EmployeesReportModel = {
  dropped_out: "",
  dropped_out_year: "",
  hired: "",
  hired_year: "",
  // hired_year: "",
  vacancies: "23",
  vacancies_year: "Х",
  civil_workers: "",
  civil_workers_year: "",
};

export const MOCK_INSTITUTIONS: Array<InstitutionModel> = [
  {
    guid: "569bc2be-52ca-11ea-a6ae-1c1b0ded7778",
    name: 'РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990140003130",
  },
  {
    guid: "36f549c5-683e-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Сигнал" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "060441013160",
  },
  {
    guid: "44c45cd7-6849-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Автоматика" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990141006180",
  },
  {
    guid: "7a3035e7-684f-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Орбита" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990141005965",
  },
  {
    guid: "41b8e67d-6850-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Высота" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990141006051",
  },
  {
    guid: "13e7c5d6-6851-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Беркут" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990241007905",
  },
  {
    guid: "f0e8f13c-6852-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Комета" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990141006100",
  },
  {
    guid: "96c6352b-6853-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Целина" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990141006130",
  },
  {
    guid: "1d140e18-6859-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Стрела" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990241007886",
  },
  {
    guid: "2a367198-6865-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Балхаш" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "990241009317",
  },
  {
    guid: "24161cbe-6867-11ea-a6b5-1c1b0ded7778",
    name: 'Филиал "Заря" РГП на ПХВ "Резерв" КГМР МЧС РК',
    bin: "000141005910",
  },
];

export const MOCK_SALARY_SUMMARY: SalarySummaryModel = {
  accrued_total: "-68",
  accrued: {
    hazard_pay: "24773",
    qualification_bonus: "",
    performance_bonus: "4499820,1",
    vacation_compensation_dismissal: "279844,26",
    taxable_financial_aid: "117960",
    night_shift_pay: "",
    daily_salary: "",
    hourly_salary_amount: "",
    sick_leave_payment: "",
    vacation_payment: "",
    health_allowance_vacation: "",
    holiday_weekend_pay: "",
    bonus_percentage_income: "",
    bonus_fixed_amount: "",
  },
  withheld_total: "8533746,57",
  withheld: {
    medical_insurance_contributions: "787466",
    individual_income_tax: "3 206 808,19",
    mandatory_pension_contributions: "4275903,98",
    union_dues: "",
    other_deductions: "",
    wage_garnishment: "263568,4",
  },
  transferred_total: "45865256,61",
  transferred: {
    bank_transfer: "36368086,68",
  },
  balance_at_end: {
    social_tax: "2521447,24",
    social_contributions: "1879887",
    employer_medical_insurance_contributions: "787466",
    employer_mandatory_pension_contributions: "4275903,98",
  },
};

export const MOCK_MATERIAL_REPORT: Array<MaterialReportModel> = [
  {
    responsible_person: "АШЛЯЕВ РУСЛАН ТЕМИРЖАНОВИЧ",
    total_balance_start_qty: 0,
    balance_start_sum: 0,
    turnover_debit_qty: 0,
    turnover_debit_sum: 0,
    turnover_credit_qty: 0,
    turnover_credit_sum: 0,
    balance_end_qty: 25,
    balance_end_sum: 5507059.68,
    departments: [
      {
        department_name: "Центр оперативного управления",
        total_balance_start_qty: 0,
        balance_start_sum: 0,
        turnover_debit_qty: 0,
        turnover_debit_sum: 0,
        turnover_credit_qty: 0,
        turnover_credit_sum: 0,
        balance_end_qty: 25,
        balance_end_sum: 5507059.68,
        row_number: [
          {
            row_number: "1",
            item_name: "Блок питания Рапан-40",
            nomenclature_number: "241300000096",
            unit: "",
            price: "19 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 19000,
          },
          {
            row_number: "2",
            item_name: "Видеодомофон с электромагнитным ключем",
            nomenclature_number: "241000000216",
            unit: "",
            price: "50 523",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 50523,
          },
          {
            row_number: "3",
            item_name: "Конвертор PERCo АC02 1-01",
            nomenclature_number: "241300000063",
            unit: "",
            price: "29 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 29000,
          },
          {
            row_number: "4",
            item_name: "Металлодетектор рамочный CELA Classic",
            nomenclature_number: "241000000240",
            unit: "",
            price: "429 511",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 429511,
          },
          {
            row_number: "5",
            item_name: "Оборуд. пожарно-охранной сигнализации",
            nomenclature_number: "241000000241",
            unit: "",
            price: "208 184",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 208184,
          },
          {
            row_number: "6",
            item_name: "программное обеспечение Тип 1",
            nomenclature_number: "273000000095",
            unit: "",
            price: "183 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 183000,
          },
          {
            row_number: "7",
            item_name: "программное обеспечение Тип 1",
            nomenclature_number: "273000000096",
            unit: "",
            price: "183 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 183000,
          },
          {
            row_number: "8",
            item_name: "программное обеспечение Тип 1",
            nomenclature_number: "273000000097",
            unit: "",
            price: "183 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 183000,
          },
          {
            row_number: "9",
            item_name: "программное обеспечение Тип 1",
            nomenclature_number: "273000000098",
            unit: "",
            price: "183 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 183000,
          },
          {
            row_number: "10",
            item_name: "программное обеспечение Тип 1",
            nomenclature_number: "273000000099",
            unit: "",
            price: "183 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 183000,
          },
          {
            row_number: "11",
            item_name: "программное обеспечение Тип 2",
            nomenclature_number: "273000000100",
            unit: "",
            price: "186 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 186000,
          },
          {
            row_number: "12",
            item_name: "программное обеспечение Тип 2",
            nomenclature_number: "273000000101",
            unit: "",
            price: "186 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 186000,
          },
          {
            row_number: "13",
            item_name: "программное обеспечение Тип 2",
            nomenclature_number: "273000000102",
            unit: "",
            price: "186 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 186000,
          },
          {
            row_number: "14",
            item_name: "программное обеспечение Тип 2",
            nomenclature_number: "273000000103",
            unit: "",
            price: "186 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 186000,
          },
          {
            row_number: "15",
            item_name: "программное обеспечение Тип 2",
            nomenclature_number: "273000000104",
            unit: "",
            price: "186 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 186000,
          },
          {
            row_number: "16",
            item_name: "программное обеспечение Тип 3",
            nomenclature_number: "273000000105",
            unit: "",
            price: "145 200",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 145200,
          },
          {
            row_number: "17",
            item_name: "программное обеспечение Тип 3",
            nomenclature_number: "273000000106",
            unit: "",
            price: "145 200",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 145200,
          },
          {
            row_number: "18",
            item_name: "программное обеспечение Тип 3",
            nomenclature_number: "273000000107",
            unit: "",
            price: "145 200",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 145200,
          },
          {
            row_number: "19",
            item_name: "программное обеспечение Тип 3",
            nomenclature_number: "273000000108",
            unit: "",
            price: "145 200",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 145200,
          },
          {
            row_number: "20",
            item_name: "программное обеспечение Тип 3",
            nomenclature_number: "273000000109",
            unit: "",
            price: "145 200",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 145200,
          },
          {
            row_number: "21",
            item_name: "Система контроля и управления доступом",
            nomenclature_number: "241000000246",
            unit: "",
            price: "789 012",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 789012,
          },
          {
            row_number: "22",
            item_name: "Система охранной сигнализации",
            nomenclature_number: "241000000247",
            unit: "",
            price: "557 829,68",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 557829.68,
          },
          {
            row_number: "23",
            item_name: "телефон сотовой связи ",
            nomenclature_number: "241300003353",
            unit: "",
            price: "97 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 97000,
          },
          {
            row_number: "24",
            item_name: "Терминал распознавания лица Hikvision DS-K1T671M",
            nomenclature_number: "241300000074",
            unit: "",
            price: "378 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 378000,
          },
          {
            row_number: "25",
            item_name: "Терминал распознавания лица Hikvision DS-K1T671M",
            nomenclature_number: "241300000075",
            unit: "",
            price: "378 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 1,
            balance_end_sum: 378000,
          },
        ],
      },
    ],
  },
  {
    responsible_person: "Бозжигитов Бауржан Жексембаевич",
    total_balance_start_qty: 5,
    balance_start_sum: 2035059.68,
    turnover_debit_qty: 0,
    turnover_debit_sum: 0,
    turnover_credit_qty: 0,
    turnover_credit_sum: 0,
    balance_end_qty: 0,
    balance_end_sum: 0,
    departments: [
      {
        department_name: "Центр оперативного управления",
        total_balance_start_qty: 5,
        balance_start_sum: 2035059.68,
        turnover_debit_qty: 0,
        turnover_debit_sum: 0,
        turnover_credit_qty: 0,
        turnover_credit_sum: 0,
        balance_end_qty: 0,
        balance_end_sum: 0,
        row_number: [
          {
            row_number: "26",
            item_name: "Видеодомофон с электромагнитным ключем",
            nomenclature_number: "241000000216",
            unit: "",
            price: "50 523",
            total_balance_start_qty: 1,
            balance_start_sum: 50523,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 0,
            balance_end_sum: 0,
          },
          {
            row_number: "27",
            item_name: "Металлодетектор рамочный CELA Classic",
            nomenclature_number: "241000000240",
            unit: "",
            price: "429 511",
            total_balance_start_qty: 1,
            balance_start_sum: 429511,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 0,
            balance_end_sum: 0,
          },
          {
            row_number: "28",
            item_name: "Оборуд. пожарно-охранной сигнализации",
            nomenclature_number: "241000000241",
            unit: "",
            price: "208 184",
            total_balance_start_qty: 1,
            balance_start_sum: 208184,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 0,
            balance_end_sum: 0,
          },
          {
            row_number: "29",
            item_name: "Система контроля и управления доступом",
            nomenclature_number: "241000000246",
            unit: "",
            price: "789 012",
            total_balance_start_qty: 1,
            balance_start_sum: 789012,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 0,
            balance_end_sum: 0,
          },
          {
            row_number: "30",
            item_name: "Система охранной сигнализации",
            nomenclature_number: "241000000247",
            unit: "",
            price: "557 829,68",
            total_balance_start_qty: 1,
            balance_start_sum: 557829.68,
            turnover_debit_qty: 0,
            turnover_debit_sum: 0,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 0,
            balance_end_sum: 0,
          },
        ],
      },
    ],
  },
  {
    responsible_person: "Кошеков Нурлан Самарбекович",
    total_balance_start_qty: 0,
    balance_start_sum: 0,
    turnover_debit_qty: 1,
    turnover_debit_sum: 97000,
    turnover_credit_qty: 0,
    turnover_credit_sum: 0,
    balance_end_qty: 0,
    balance_end_sum: 0,
    departments: [
      {
        department_name: "Центр оперативного управления",
        total_balance_start_qty: 0,
        balance_start_sum: 0,
        turnover_debit_qty: 1,
        turnover_debit_sum: 97000,
        turnover_credit_qty: 0,
        turnover_credit_sum: 0,
        balance_end_qty: 0,
        balance_end_sum: 0,
        row_number: [
          {
            row_number: "958",
            item_name: "телефон сотовой связи ",
            nomenclature_number: "241300003353",
            unit: "",
            price: "97 000",
            total_balance_start_qty: 0,
            balance_start_sum: 0,
            turnover_debit_qty: 1,
            turnover_debit_sum: 97000,
            turnover_credit_qty: 0,
            turnover_credit_sum: 0,
            balance_end_qty: 0,
            balance_end_sum: 0,
          },
        ],
      },
    ],
  },
];

export const MOCK_ASSETS: {
  data: Array<AssetsModel>;
  report_date: string;
} = {
  data: [
    {
      code: "010",
      start_period_value: "218994215,98",
      end_period_value: "559766880,25",
    },
    {
      code: "011",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "012",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "013",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "014",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "015",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "016",
      start_period_value: "23776128,15",
      end_period_value: "3162960,07",
    },
    {
      code: "017",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "018",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "019",
      start_period_value: "71640057,77",
      end_period_value: "71640057,77",
    },
    {
      code: "020",
      start_period_value: "75047642,43",
      end_period_value: "12620333,31",
    },
    {
      code: "021",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "022",
      start_period_value: "372197952,36",
      end_period_value: "118192874,62",
    },
    {
      code: "110",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "111",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "112",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "113",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "114",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "115",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "116",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "117",
      start_period_value: "-744693",
      end_period_value: "",
    },
    {
      code: "118",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "119",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "120",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "121",
      start_period_value: "607638847,55",
      end_period_value: "258403810,09",
    },
    {
      code: "122",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "123",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "124",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "125",
      start_period_value: "25502706,6",
      end_period_value: "30299335,04",
    },
    {
      code: "126",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "127",
      start_period_value: "97226772,06",
      end_period_value: "97226772,06",
    },
    {
      code: "210",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "211",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "212",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "213",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "214",
      start_period_value: "234363617,1",
      end_period_value: "14130406,7",
    },
    {
      code: "215",
      start_period_value: "37985282,57",
      end_period_value: "28679703,86",
    },
    {
      code: "216",
      start_period_value: "32570733",
      end_period_value: "32570733",
    },
    {
      code: "217",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "218",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "219",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "222",
      start_period_value: "168390449,25",
      end_period_value: "0,02",
    },
    {
      code: "301",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "310",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "311",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "312",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "313",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "314",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "315",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "316",
      start_period_value: "334096260,61",
      end_period_value: "334096260,61",
    },
    {
      code: "317",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "318",
      start_period_value: "563380216,42",
      end_period_value: "",
    },
    {
      code: "319",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "321",
      start_period_value: "98291778,2",
      end_period_value: "214386053,5",
    },
    {
      code: "410",
      start_period_value: "1793111191,02",
      end_period_value: "1793111191,02",
    },
    {
      code: "411",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "412",
      start_period_value: "",
      end_period_value: "",
    },
    {
      code: "413",
      start_period_value: "1634329,12",
      end_period_value: "1634329,12",
    },
    {
      code: "414",
      start_period_value: "-1772544227,39",
      end_period_value: "-1267295654,62",
    },
    {
      code: "415",
      start_period_value: "",
      end_period_value: "",
    },
  ],
  report_date: "05.06.2025",
};
