import {
  EmployeesReportModel,
  InstitutionModel,
  StaffInfoModel,
  StaffModel,
  StaffMovementModel,
  StaffSalaryModel,
} from "@/lib/api-service";

// Mock data for testing
export const MOCK_STAFF_DATA: Array<StaffModel> = [
  {
    staff_id: "900815300455",
    firstname: "Динара",
    lastname: "Жарасова",
    department: "Отдел разработки",
    institution: "Учреждение А",
    gender: "female",
  },
  {
    staff_id: "881220300455",
    firstname: "Алишер",
    lastname: "Ибраев",
    department: "Отдел маркетинга",
    institution: "Учреждение Б",
    gender: "male",
  },
  {
    staff_id: "920410300455",
    firstname: "Айгуль",
    lastname: "Нурланова",
    department: "Отдел продаж",
    institution: "Учреждение А",
    gender: "female",
  },
  {
    staff_id: "870725300455",
    firstname: "Марат",
    lastname: "Садыков",
    department: "Отдел разработки",
    institution: "Учреждение Б",
    gender: "male",
  },
];

// Mock data for staff info
export const MOCK_STAFF_INFO: Array<StaffInfoModel> = [
  {
    full_name: "Жарасова Динара Алиевна",
    position: "Ведущий разработчик",
    institution: "Учреждение А",
    department: "Отдел разработки",
    salary: 450000,
    birth_date: "1990-08-15",
    gender: "Женский",
    nationality: "Казашка",
    id_number: "900815300455",
    worker_type: "Постоянный сотрудник",
    hire_date: "2018-03-01",
    education: "Высшее",
    birthplace: "г. Алматы",
    phone: "+7 701 234 56 78",
    mail: "zharasova@example.com",
    schedule_type: "Пятидневная рабочая неделя",
    worked_out: "19/20",
  },
  {
    full_name: "Ибраев Алишер Маратович",
    position: "Маркетолог",
    institution: "Учреждение Б",
    department: "Отдел маркетинга",
    salary: 380000,
    birth_date: "1988-12-20",
    gender: "Мужской",
    nationality: "Казах",
    id_number: "881220300455",
    worker_type: "Постоянный сотрудник",
    hire_date: "2019-06-15",
    education: "Высшее",
    birthplace: "г. Астана",
    phone: "+7 702 345 67 89",
    mail: "ibraev@example.com",
    schedule_type: "Пятидневная рабочая неделя",
    worked_out: "18/20",
  },
  {
    full_name: "Нурланова Айгуль Сериковна",
    position: "Менеджер по продажам",
    institution: "Учреждение А",
    department: "Отдел продаж",
    salary: 420000,
    birth_date: "1992-04-10",
    gender: "Женский",
    nationality: "Казашка",
    id_number: "920410300455",
    worker_type: "Постоянный сотрудник",
    hire_date: "2020-01-10",
    education: "Высшее",
    birthplace: "г. Караганда",
    phone: "+7 705 456 78 90",
    mail: "nurlanova@example.com",
    schedule_type: "Пятидневная рабочая неделя",
    worked_out: "20/20",
  },
  {
    full_name: "Садыков Марат Аскарович",
    position: "Старший разработчик",
    institution: "Учреждение Б",
    department: "Отдел разработки",
    salary: 480000,
    birth_date: "1987-07-25",
    gender: "Мужской",
    nationality: "Казах",
    id_number: "870725300455",
    worker_type: "Постоянный сотрудник",
    hire_date: "2017-09-01",
    education: "Высшее",
    birthplace: "г. Шымкент",
    phone: "+7 707 567 89 01",
    mail: "sadykov@example.com",
    schedule_type: "Пятидневная рабочая неделя",
    worked_out: "17/20",
  },
];

// Mock data for staff movements
export const MOCK_STAFF_MOVEMENTS: Array<StaffMovementModel> = [
  {
    position: "Младший разработчик",
    institution: "Учреждение А",
    date: "2018-03-01",
    department: "Отдел разработки",
    worker_type: "Постоянный сотрудник",
    event: "Принят на работу",
    document: "Приказ №123 от 01.03.2018",
  },
  {
    position: "Разработчик",
    institution: "Учреждение А",
    date: "2020-05-15",
    department: "Отдел разработки",
    worker_type: "Постоянный сотрудник",
    event: "Повышение",
    document: "Приказ №456 от 15.05.2020",
  },
  {
    position: "Ведущий разработчик",
    institution: "Учреждение А",
    date: "2022-11-10",
    department: "Отдел разработки",
    worker_type: "Постоянный сотрудник",
    event: "Повышение",
    document: "Приказ №789 от 10.11.2022",
  },
  {
    position: "Младший маркетолог",
    institution: "Учреждение Б",
    date: "2019-06-15",
    department: "Отдел маркетинга",
    worker_type: "Постоянный сотрудник",
    event: "Принят на работу",
    document: "Приказ №234 от 15.06.2019",
  },
  {
    position: "Маркетолог",
    institution: "Учреждение Б",
    date: "2021-09-01",
    department: "Отдел маркетинга",
    worker_type: "Постоянный сотрудник",
    event: "Повышение",
    document: "Приказ №567 от 01.09.2021",
  },
  {
    position: "Менеджер по продажам",
    institution: "Учреждение А",
    date: "2020-01-10",
    department: "Отдел продаж",
    worker_type: "Постоянный сотрудник",
    event: "Принят на работу",
    document: "Приказ №345 от 10.01.2020",
  },
  {
    position: "Инженер-программист",
    institution: "РГП Стрела",
    date: "2017-09-01",
    department: "Отдел разработки",
    worker_type: "Постоянный сотрудник",
    event: "Принят на работу",
    document: "Приказ №678 от 01.09.2017",
  },
  {
    position: "Старший инженер",
    institution: "РГП Балхаш",
    date: "2021-02-01",
    department: "Отдел разработки",
    worker_type: "Постоянный сотрудник",
    event: "Перевод в другое учреждение",
    document: "Приказ №901 от 01.02.2021",
  },
  {
    position: "Старший разработчик",
    institution: "Учреждение Б",
    date: "2023-06-15",
    department: "Отдел разработки",
    worker_type: "Постоянный сотрудник",
    event: "Перевод в другое учреждение",
    document: "Приказ №234 от 15.06.2023",
  },
];

// Mock data for staff salaries
export const MOCK_STAFF_SALARIES: StaffSalaryModel[] = [
  {
    position: "Разработчик",
    department: "IT",
    salary_type: "Основное начисление",
    positions_amount: 3,
    salary: 150000,
  },
  {
    position: "Тестировщик",
    department: "QA",
    salary_type: "Основное начисление",
    positions_amount: 2,
    salary: 120000,
  },
  {
    position: "Менеджер проекта",
    department: "Менеджмент",
    salary_type: "Основное начисление",
    positions_amount: 1,
    salary: 230000,
  },
  {
    position: "Дизайнер",
    department: "Дизайн",
    salary_type: "Основное начисление",
    positions_amount: 2,
    salary: 140000,
  },
  {
    position: "Системный администратор",
    department: "IT",
    salary_type: "Основное начисление",
    positions_amount: 1,
    salary: 180000,
  },
  {
    position: "Старший разработчик",
    department: "IT",
    salary_type: "Основное начисление",
    positions_amount: 2,
    salary: 220000,
  },
  {
    position: "HR менеджер",
    department: "HR",
    salary_type: "Основное начисление",
    positions_amount: 1,
    salary: 170000,
  },
];

// Mock employee report data
export const MOCK_EMPLOYEE_REPORT: EmployeesReportModel = {
  dropped_out: 15,
  dropped_out_year: 25,
  hired: 20,
  hired_year: 35,
  vacancies: 10,
  vacancies_year: 18,
  civil_workers: 5,
  civil_workers_year: 8,
};

export const MOCK_INSTITUTIONS: Array<InstitutionModel> = [
  {
    guid: "1",
    bin: "123",
    name: 'РГП на ПХВ "Резерва МЧС РК; Филиал..."',
  },
  {
    guid: "2",
    bin: "1234",
    name: "Филиал в городе Астана",
  },
  {
    guid: "3",
    bin: "12345",
    name: "Филиал в городе Алматы",
  },
  {
    guid: "4",
    bin: "123456",
    name: "Филиал в Карагандинской области",
  },
  {
    guid: "5",
    bin: "1234567",
    name: "Филиал в Актюбинской области",
  },
];

export const MOCK_SALARY_SUMMARY: any = {
  genderStats: {
    total: 97,
    men: 57,
    women: 40,
  },
  salaryRange: {
    average: 180000.0,
    high: 300000.0,
    low: 130000.0,
  },
  salarySummary: {
    accrued: 971096193.46,
    withheld: 43585304.5,
    transferred: 1789111191.02,
  },
};
